# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 20

#[[main]]
#  name = "Projetos"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publicações"
#  url = "#publications"
#  weight = 40

[[main]]
  name = "O que aprender"
  url = "#"
  hasChildren = true
  weight = 50
  
[[main]]
  parent = "O que aprender"
  name = "Logística Urbana"
  url = "conteudo/log_urb/"
  weight = 10
  
[[main]]
  parent = "O que aprender"
  name = "Acessibilidade"
  url = "conteudo/access/"
  weight = 20

[[main]]
  parent = "O que aprender"
  name = "Ciência de dados"
  url = "conteudo/data/"
  weight = 30
  
[[main]]
  parent = "O que aprender"
  name = "Introdução ao R"
  url = "conteudo/intro_r/"
  weight = 40
  
[[main]]
  parent = "O que aprender"
  name = "Análise espacial"
  url = "conteudo/spatial/"
  weight = 50
  
[[main]]
  parent = "O que aprender"
  name = "Urban Analytics"
  url = "conteudo/urban/"
  weight = 60

[[main]]
  name = "Como aprender"
  url = "#"
  hasChildren = true
  weight = 60

[[main]]
  parent = "Como aprender"
  name = "Logística - 2021/1"
  url = "courses/log/"
  weight = 10
  
[[main]]
  parent = "Como aprender"
  name = "Métodos Quantitativos para Suporte à Decisão na Gestão Urbana - 2021/1"
  url = "courses/urban_analytics/"
  weight = 20
  
[[main]]
  parent = "Como aprender"
  name = "Análise de Dados para gestão organizacional - 2021/1"
  url = "courses/dados_grad/"
  weight = 30

[[main]]
  parent = "Como aprender"
  name = "Análise de Dados aplicada ao processo decisório - 2020/2"
  url = "courses/dados_pos/"
  weight = 40
  
[[main]]
  name = "Contato"
  url = "#contact"
  weight = 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 80
