[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.91.2'


[context]
[context.production.environment]
  HUGO_VERSION = "0.91.2" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  

