---
date: "2020-12-275T00:00:00+01:00"
draft: false
menu:
  log:
    parent: Estudos autônomos
    weight: 6
title: KPIs
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 20
---

# Responda as questões a seguir de maneira colaborativa em seu grupo de trabalho e submeta pela respectiva tarefa do SIGAA.

1.  O que são e qual a importância de KPIs para a gestão da cadeia de
    suprimentos?

2.  Você trabalha na empresa Entrega Rápida que atua no mercado como
    operador logístico para e-commerce. Você tem três clientes
    majoritários, a saber: (i) portoriquenhos.com; (ii)
    submarinonuclear.com; e (iii) purchasetime.com. Para estes
    clientes você, como analista de transporte, deve gerenciar a
    cadeia de suprimentos e, em especial, a distribuição no último
    quilômetro a fim de obter a melhor relação custo/benefício da
    operação (os menores custos possíveis com o maior nível de
    serviço, adequado às expectativas dos varejistas e dos
    consumidores finais). Entretanto, você trabalhará sozinho no
    controle da entrega de último quilômetro para os clientes desses
    três varejistas, e há escassez de mão de obra alocada para esse
    processo gerencial.

Assim, será possível escolher apenas três indicadores de desempenho
(KPI) para todas as classes de atributos a serem monitorados:

(i) desempenho no atendimento ao cliente\
(ii) desempenho na gestão de estoques\
(iii) produtividade do armazém\
(iv) desempenho em transportes

Destaca-se a importância do trade-off (custo operacional x nível de
serviço). Você poderá escolher, dentre os indicadores apresentados na
tabela apresentada ao final desta atividade, três indicadores de forma
a completar a visão gerencial do seu processo. Quais são esses três
indicadores e por que você os escolheu? Lembre-se que são apenas três
indicadores para todas as classes de atributos a serem monitorados.

## KPI's Logísticos

+------------+--------------+------------------+-------------+
| Indicador  | Descrição    | Cálculo          | Melhores    |
| de D       |              |                  | Práticas    |
| esempenho  |              |                  |             |
+============+==============+==================+=============+
| D          |              |                  |             |
| ESEMPENHO  |              |                  |             |
| NO A T     |              |                  |             |
| ENDIMENTO  |              |                  |             |
| DO PEDIDO  |              |                  |             |
| DO CLIENTE |              |                  |             |
+------------+--------------+------------------+-------------+
| Pedido     | Calcula a    | \% acurácia no   | Em torno de |
| Perfeito   | taxa de      | Registro do      | 70%.        |
| ou Perfect | pedidos sem  | Pedido x %       |             |
| Order Me   | erros em     | acurácia na      | |           |
| asurement  | cada estágio | Separação x % \| |             |
|            | do pedido do | Entregas no      |             |
|            | Cliente.     | Prazo x %        |             |
|            | Deve         | Entregas sem     |             |
|            | considerar   | Danos x %        |             |
|            | cada etapa   | Pedidos          |             |
|            | na "vida" de | Faturados        |             |
|            | um pedido.   | Corretamente.    |             |
+------------+--------------+------------------+-------------+
| \% de      | Corresponde  | Entregas         | Para grupos |
| Pedidos    | às entregas  | Perfeitas /      | de Clientes |
| Completos  | realizadas   | Total de         | A, o índice |
| e no Prazo | dentro do    | Entregas         | varia de    |
| ou % OTIF  | prazo e      | Realizadas.      | 90% a 95%;  |
| - On Time  | atendendo as |                  | no geral    |
| in Full    | quantidades  |                  | atinge      |
|            | e            |                  | valores     |
|            | es           |                  | próximos de |
|            | pecificações |                  | 75%.        |
|            | do pedido.   |                  |             |
+------------+--------------+------------------+-------------+
| \% de      | De           | Entregas no      | Variam de   |
| Entregas   | smembramento | prazo / Total de | 95% a 98%   |
| no Prazo   | da OTIF;     | Entregas         |             |
| ou On Time | mede % de    | Realizadas.      |             |
| Delivery   | entregas     |                  |             |
|            | realizadas   |                  |             |
|            | no prazo     |                  |             |
|            | acordado com |                  |             |
|            | o Cliente.   |                  |             |
+------------+--------------+------------------+-------------+
| Taxa de    | De           | Pedidos          | 99.50%      |
| A          | smembramento | integralmente    |             |
| tendimento | da OTIF;     | atendidos /      |             |
| do Pedido  | mede % de    | Total de Pedidos |             |
| ou Order   | pedidos      | Expedidos.       |             |
| Fill Rate  | atendidos na |                  |             |
|            | quantidade e |                  |             |
|            | es           |                  |             |
|            | pecificações |                  |             |
|            | solicitadas  |                  |             |
|            | pelo         |                  |             |
|            | Cliente.     |                  |             |
+------------+--------------+------------------+-------------+
| Tempo de   | Tempo        | Data da Entrega  | Menos de 24 |
| Ciclo do   | decorrido    | menos a Data da  | horas para  |
| Pedido ou  | entre a      | Realização do    | localidades |
| Order      | realização   | Pedido.          | mais        |
| Cycle Time | do pedido    |                  | próximas ou |
|            | por um       |                  | até um      |
|            | Cliente e a  |                  | limite de   |
|            | data de      |                  | 350 km.     |
|            | entrega.     |                  |             |
|            | Alguns       |                  |             |
|            | consideram   |                  |             |
|            | como data    |                  |             |
|            | final a data |                  |             |
|            | de disp      |                  |             |
|            | onibilização |                  |             |
|            | do pedido na |                  |             |
|            | doca de      |                  |             |
|            | expedição.   |                  |             |
+------------+--------------+------------------+-------------+
| D          |              |                  |             |
| ESEMPENHO  |              |                  |             |
| NA GESTÃO  |              |                  |             |
| DOS        |              |                  |             |
| ESTOQUES   |              |                  |             |
+------------+--------------+------------------+-------------+
| Dock to    | Tempo da     | Tempo da doca ao | 2 horas ou  |
| Stock Time | mercadoria   | estoque ou       | 99,9 % no   |
|            | da doca de   | disponibilização | mesmo dia.  |
|            | recebimento  | do item para     |             |
|            | até a sua    | venda.           |             |
|            | armazenagem  |                  |             |
|            | física.      |                  |             |
|            | Outros       |                  |             |
|            | consideram   |                  |             |
|            | da doca até  |                  |             |
|            | a sua        |                  |             |
|            | armazenagem  |                  |             |
|            | física e o   |                  |             |
|            | seu registro |                  |             |
|            | nos sistemas |                  |             |
|            | de controle  |                  |             |
|            | de estoques  |                  |             |
|            | e dis p      |                  |             |
|            | onibilização |                  |             |
|            | para venda.  |                  |             |
+------------+--------------+------------------+-------------+
| Acurácia   | Corresponde  | Estoque Físico   | No Brasil,  |
| do         | à diferença  | Atual por SKU /  | 95%. No     |
| Inventário | entre o      | Estoque Contábil | Japão       |
| ou         | estoque      | ou Estoque       | atingem     |
| Inventory  | físico e a   | Reportado no     | 99,95% e    |
| Accuracy   | informação   | Sistema.         | nos EUA     |
|            | contábil de  |                  | entre       |
|            | estoques.    |                  | 99,75% a    |
|            |              |                  | 99,95%.     |
+------------+--------------+------------------+-------------+
| Stock outs | Q            | Receita não      | Variável.   |
|            | uantificação | Realizada devido |             |
|            | das vendas   | à                |             |
|            | perdidas em  | I                |             |
|            | função da    | ndisponibilidade |             |
|            | indis        | do Item em       |             |
|            | ponibilidade | Estoque (R\$).   |             |
|            | do item      |                  |             |
|            | solicitado.  |                  |             |
+------------+--------------+------------------+-------------+
| Utilização | Mede a       | Ocupação Média   | Estar acima |
| da         | utilização   | em m³ ou         | de 100 % é  |
| Capacidade | volumétrica  | Posições de      | um péssimo  |
| de         | ou do número | Armazenagem      | indicador,  |
| Estocagem  | de posições  | Ocupadas /       | pois pr     |
| ou Storage | para         | Capacidade Total | ovavelmente |
| U          | estocagem    | de Armazenagem   | indica que  |
| tilization | disponíveis  | em m³ ou Número  | corredores  |
|            | em um        | de Posições.     | ou outras   |
|            | armazém.     |                  | áreas       |
|            |              |                  | inadequadas |
|            |              |                  | para        |
|            |              |                  | estocagem   |
|            |              |                  | estão sendo |
|            |              |                  | utilizadas. |
+------------+--------------+------------------+-------------+
| \% Estoque | Corresponde  | Estoque          | Variável.   |
| In         | ao estoque   | Indi             |             |
| disponível | indisponível | sponível/Estoque |             |
| para Venda | para venda   | total em reais.  |             |
|            | em função de |                  |             |
|            | danos        |                  |             |
|            | decorrentes  |                  |             |
|            | da           |                  |             |
|            | movimentação |                  |             |
|            | armazenagem, |                  |             |
|            | vencimento   |                  |             |
|            | da data de   |                  |             |
|            | validade ou  |                  |             |
|            | ob           |                  |             |
|            | solescência. |                  |             |
+------------+--------------+------------------+-------------+
| Utilização | Mede a       | Ocupação Média   | Estar acima |
| da         | utilização   | em m³ ou         | de 100% é   |
| Capacidade | volumétrica  | Posições de      | um péssimo  |
| de         | ou do número | Armazenagem      | indicador,  |
| Estocagem  | de posições  | Ocupadas /       | pois pr     |
| ou Storage | para         | Capacidade Total | ovavelmente |
| U          | estocagem    | de Armazenagem   | indica que  |
| tilization | disponíveis  | em m³ ou Número  | corredores  |
|            | em um        | de Posições.     | ou outras   |
|            | armazém.     |                  | áreas       |
|            |              |                  | inadequadas |
|            |              |                  | para        |
|            |              |                  | estocagem   |
|            |              |                  | estão sendo |
|            |              |                  | utilizadas. |
+------------+--------------+------------------+-------------+
| Vi         | Mede o tempo | Data / Hora do   | Máximo de 2 |
| sibilidade | para         | Registro da      | horas.      |
| dos        | disp         | Informação de    |             |
| Estoques   | onibilização | Recebimento do   |             |
| ou         | dos estoques | Material nos     |             |
| Inventory  | dos          | Sistemas da      |             |
| Visibility | materiais    | Empresa - Data / |             |
|            | recém        | Hora do          |             |
|            | recebidos    | Recebimento      |             |
|            | nos sistemas | Físico.          |             |
|            | da empresa.  |                  |             |
+------------+--------------+------------------+-------------+
| PROD       |              |                  |             |
| UTIVIDADE  |              |                  |             |
| DO ARMAZÉM |              |                  |             |
+------------+--------------+------------------+-------------+
| Pedidos    | Mede a       | Pedidos          | Variam      |
| por Hora   | quantidade   | Separados /      | conforme o  |
| ou Orders  | de pedidos   | Embalados /      | tipo de     |
| per Hour   | separados e  | Total de Horas   | negócio.    |
|            | embalados /  | Trabalhadas no   |             |
|            | ac           | Armazém.         |             |
|            | ondicionados |                  |             |
|            | por hora.    | Horas            |             |
|            | Também pode  | Trabalhadas no   |             |
|            | ser medido   | Armazém.         |             |
|            | em linhas ou |                  |             |
|            | itens.       |                  |             |
+------------+--------------+------------------+-------------+
| Custo por  | Rateio dos   | Custo Total do   | Variam      |
| Pedido ou  | custos       | Armazém / Total  | conforme o  |
| Cost per   | operacionais | de Pedidos       | tipo de     |
| Order      | do armazém   | Expedidos.       | negócio.    |
|            | pela         |                  |             |
|            | quantidade   |                  |             |
|            | de pedidos   |                  |             |
|            | expedidos.   |                  |             |
+------------+--------------+------------------+-------------+
| Custos de  | Revela a     | Custo Total do   | Variam      |
| Mo         | participação | Armazém / Venda  | conforme o  |
| vimentação | dos custos   | Total.           | tipo de     |
| e          | operacionais |                  | negócio.    |
| A          | de um        |                  |             |
| rmazenagem | armazém nas  |                  |             |
| como um %  | vendas de    |                  |             |
| das Vendas | uma empresa. |                  |             |
| ou         |              |                  |             |
| W          |              |                  |             |
| arehousing |              |                  |             |
| Cost as %  |              |                  |             |
| of Sales.  |              |                  |             |
+------------+--------------+------------------+-------------+
| Tempo      | Mede o tempo | Hora de Saída da | Variam      |
| Médio de   | de           | Doca - Hora de   | conforme    |
| Carga /    | permanência  | Entrada na Doca. | tipo de     |
| Descarga.  | dos veículos |                  | veículo,    |
|            | de           |                  | carga e     |
|            | transporte   |                  | condições   |
|            | nas docas de |                  | op          |
|            | recebimento  |                  | eracionais. |
|            | e expedição. |                  |             |
+------------+--------------+------------------+-------------+
| Tempo      | Além do      | Hora de Saída da | Variam      |
| Médio de   | tempo em     | Portaria - Hora  | conforme pr |
| P          | doca, mede   | de Entrada na    | ocedimentos |
| ermanência | tempos       | Portaria.        | da empresa. |
| do Veículo | manobra,     |                  |             |
| de         | trânsito     |                  |             |
| Transporte | interno,     |                  |             |
| ou Truck   | autorização  |                  |             |
| Turnaround | da Portaria, |                  |             |
| Time       | vistorias,   |                  |             |
|            | etc.         |                  |             |
+------------+--------------+------------------+-------------+
| Utilização | Horas em     | Em uso           |             |
| dos        | Operação /   | intensivo, com   |             |
| Eq         | Horas        | operador         |             |
| uipamentos | Disponíveis  | dedicado, mínimo |             |
| de         | para Uso.    | de 95%.          |             |
| Mo         |              |                  |             |
| vimentação |              |                  |             |
| Mede a     |              |                  |             |
| utilização |              |                  |             |
| dos        |              |                  |             |
| eq         |              |                  |             |
| uipamentos |              |                  |             |
| de         |              |                  |             |
| mo         |              |                  |             |
| vimentação |              |                  |             |
| d          |              |                  |             |
| isponíveis |              |                  |             |
| em uma     |              |                  |             |
| operação   |              |                  |             |
| de         |              |                  |             |
| mo         |              |                  |             |
| vimentação |              |                  |             |
| e arm      |              |                  |             |
| azenagem.  |              |                  |             |
+------------+--------------+------------------+-------------+
| DESEMPENHO |              |                  |             |
| EM TR      |              |                  |             |
| ANSPORTES  |              |                  |             |
+------------+--------------+------------------+-------------+
| Custos de  | Mostra a     | Custo Total de   | Variam      |
| Transporte | participação | Transportes /    | conforme o  |
| como um %  | dos custos   | Vendas Totais em | tipo de     |
| das Vendas | de           | reais.           | negócio.    |
| ou Freight | transportes  |                  |             |
| Costs as % | nas vendas   |                  |             |
| of Sales.  | totais da    |                  |             |
|            | empresa.     |                  |             |
+------------+--------------+------------------+-------------+
| Custo do   | Revela o     | Custo Total de   | Variam      |
| Frete por  | custo do     | Transporte /     | conforme o  |
| Unidade    | frete por    | Total de         | tipo de     |
| Expedida   | unidade      | Unidades         | negócio.    |
| ou Freight | expedida.    | Expedidas.       |             |
| Cost per   | Pode também  |                  |             |
| Unit       | ser          |                  |             |
| Shipped.   | calculado    |                  |             |
|            | por modo de  |                  |             |
|            | transporte.  |                  |             |
+------------+--------------+------------------+-------------+
| Coletas no | Calcula o %  | Coletas no prazo | Variam de   |
| Prazo ou   | de coletas   | / Total de       | 95% a 98%.  |
| On Time    | realizadas   | coletas.         |             |
| Pickups.   | dentro do    |                  |             |
|            | prazo        |                  |             |
|            | acordado.    |                  |             |
+------------+--------------+------------------+-------------+
| Utilização | Avalia a     | Carga Total      | Depende de  |
| da         | utilização   | Expedida /       | diversas    |
| Capacidade | da           | Capacidade       | variáveis,  |
| de Carga   | capacidade   | Teórica Total    | mas as      |
| de         | de carga dos | dos Veículos     | melhores    |
| Caminhões  | veículos de  | Utilizados.      | práticas    |
| ou         | transporte   |                  | estão ao    |
| Truckload  | utilizados.  |                  | redor de    |
| Capacity   |              |                  | 85%.        |
| Utilized   |              |                  |             |
+------------+--------------+------------------+-------------+
| Avarias no | Mede a       | Avarias no       | Variável.   |
| Transporte | participação | Transporte /     |             |
| ou Damages | das avarias  | Total Expedido   |             |
|            | em           | em reais         |             |
|            | transporte   |                  |             |
|            | no total     |                  |             |
|            | expedido.    |                  |             |
+------------+--------------+------------------+-------------+
| Não        | Mede a       | Custo Adicional  | Variável.   |
| Con        | participação | de Frete com Não |             |
| formidades | do custo     | Conformidades /  |             |
| em         | extra de     | Custo Total de   |             |
| T          | frete        | Transporte em    |             |
| ransportes | decorrente   | reais            |             |
|            | de           |                  |             |
|            | re-entregas, |                  |             |
|            | devoluções,  |                  |             |
|            | atrasos, etc |                  |             |
|            | por motivos  |                  |             |
|            | diversos no  |                  |             |
|            | custo total  |                  |             |
|            | de           |                  |             |
|            | transporte.  |                  |             |
+------------+--------------+------------------+-------------+
| A          | Mede a       | Erros na         | Mínimo de   |
| curacidade | participação | Cobrança / Custo | 98,5%.      |
| no Co      | dos erros    | Total de         |             |
| nhecimento | verificados  | Transporte em    |             |
| de Frete   | no           | reais.           |             |
| ou Freight | conhecimento |                  |             |
| Bill       | de frete em  |                  |             |
| Accuracy   | relação aos  |                  |             |
|            | custos       |                  |             |
|            | totais de    |                  |             |
|            | transportes. |                  |             |
+------------+--------------+------------------+-------------+
